### ISSUE TITLE
Add Norwegian Personal Number

### ISSUE THREAD

**Issue by kutyel** [niho/personal-number#1]
Would you mind us doing a PR to this lib? 👀

**Comment by niho** [comment]
@kutyel Please, be my guest. PRs are welcome.

Are you using Elm at Scrive?

**Comment by kutyel** [comment]
Yup, extensively! 🙌🏻

**Comment by niho** [comment]
@kutyel Cool! Are you looking for developers? I've been working professionally with Elm since 2015 and I'm currently available for hire, if you're interested.

**Comment by kraklin** [comment]
@niho we might have an opening soon. I would post it to elm jobs slack channel for sure when it will be official. Waiting for sign off right now

**Comment by niho** [comment]
@kraklin Ok, I'm a freelancer, so very flexible with whatever you might need help with. Full time, part time, shorter projects, whatever. I don't keep up with the Elm slack, so might miss the post. But you're welcome to get in touch whenever you might need an extra hand (you can find my contact details on my website, link in profile).

**Comment by kraklin** [comment]
cool, I would let you know then when the posting is out ;)
