### ISSUE TITLE
Release new version with PersonalNumber.Norwegian

### ISSUE THREAD

**Issue by kutyel** [niho/personal-number#5]
🙏🏻

**Comment by niho** [comment]
It's released, but not showing up as the latest version on package.elm-lang.org. I guess it's  some kind of cache issue?

https://package.elm-lang.org/packages/niho/personal-number/1.2.1/

**Comment by kutyel** [comment]
Interesting! @kraklin do you know why? when I enter the website it keeps saying latest version is 1.0.0 🤔 (I never released an elm package before)

**Comment by kutyel** [comment]
Dependabot picked it up and it works correctly, thanks!
